/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "pic_data_constants.h"



const pic_dataConstants g_pic_data_constants;

pic_dataConstants::pic_dataConstants() {
}



