/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef pic_data_CONSTANTS_H
#define pic_data_CONSTANTS_H

#include "pic_data_types.h"



class pic_dataConstants {
 public:
  pic_dataConstants();

};

extern const pic_dataConstants g_pic_data_constants;



#endif
